#!/usr/bin/env python3
"""
deploy_dbt.py — Deploy and build the apc dbt pipeline.

Usage:
    python3 deploy_dbt.py [-c <connection>]
    python3 deploy_dbt.py -c <your-connection> -D "dbt_account=myaccount" -D "dbt_role=SYSADMIN"

Steps:
  1. Reads vars.yaml for database/warehouse/dbt identity defaults.
  2. If dbt_account/user/role are blank, auto-detects from the active snow connection.
  3. Writes dbt/apc/profiles.yml with the resolved values.
  4. Creates DBT_ANALYTICS schema.
  5. Runs: snow dbt deploy → snow dbt execute ... build
"""
import json, subprocess, sys, yaml
from pathlib import Path

ROOT = Path(__file__).parent
PROFILES = ROOT / "dbt" / "apc" / "profiles.yml"


def parse_args():
    overrides, conn, rest = {}, None, []
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "-D" and i + 1 < len(args):
            k, _, v = args[i + 1].partition("=")
            overrides[k.strip()] = v.strip()
            i += 2
        elif args[i] in ("-c", "--connection") and i + 1 < len(args):
            conn = args[i + 1]
            i += 2
        else:
            rest.append(args[i])
            i += 1
    return overrides, conn, rest


def run_cmd(args, label=None, capture=False):
    if label:
        print(f"\n→ {label}")
    r = subprocess.run(args, capture_output=capture, text=capture)
    if r.returncode != 0:
        if capture:
            print(r.stderr, file=sys.stderr)
        print(f"ERROR: command failed (exit {r.returncode})", file=sys.stderr)
        sys.exit(1)
    return r.stdout if capture else None


def detect_session(conn):
    print("Auto-detecting account/user/role from active session...")
    cmd = ["snow", "sql"]
    if conn:
        cmd += ["-c", conn]
    cmd += ["-q",
            "SELECT CURRENT_ACCOUNT() AS A, CURRENT_USER() AS U, CURRENT_ROLE() AS R",
            "--format", "json"]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(f"ERROR: {r.stderr}", file=sys.stderr)
        sys.exit(1)
    row = json.loads(r.stdout)[0]
    return row["A"].lower(), row["U"], row["R"]


def write_profiles(account, user, role, database, warehouse):
    content = f"""# profiles.yml — auto-generated by deploy_dbt.py
# Edit vars.yaml to change identity or pass -D flags to override.
default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: {account}
      user: {user}
      role: {role}
      database: {database}
      warehouse: {warehouse}
      schema: DBT_ANALYTICS
      threads: 4
"""
    PROFILES.write_text(content)
    print(f"  profiles.yml written: account={account}  user={user}  role={role}")
    print(f"                        database={database}  warehouse={warehouse}")


def main():
    overrides, conn, _ = parse_args()

    with open(ROOT / "vars.yaml") as f:
        vars_data = yaml.safe_load(f)
    vars_data.update(overrides)

    database  = vars_data.get("database", "APC_DEPLOY_DB")
    warehouse = vars_data.get("warehouse", "APC_DEPLOY_WH")
    dbt_account = str(vars_data.get("dbt_account", "")).strip()
    dbt_user    = str(vars_data.get("dbt_user",    "")).strip()
    dbt_role    = str(vars_data.get("dbt_role",    "")).strip()

    if not dbt_account or not dbt_user or not dbt_role:
        a, u, r = detect_session(conn)
        dbt_account = dbt_account or a
        dbt_user    = dbt_user    or u
        dbt_role    = dbt_role    or r

    write_profiles(dbt_account, dbt_user, dbt_role, database, warehouse)

    # Clear compiled artifacts — snow CLI 3.20 path bug triggered by target/ dir
    import shutil
    target_dir = ROOT / "dbt" / "apc" / "target"
    if target_dir.exists():
        shutil.rmtree(target_dir)
        print("  Cleared dbt/apc/target/ (prevents snow CLI path bug)")

    # Create schema
    schema_cmd = ["snow", "sql"]
    if conn:
        schema_cmd += ["-c", conn]
    schema_cmd += ["-q", f"CREATE SCHEMA IF NOT EXISTS {database}.DBT_ANALYTICS"]
    run_cmd(schema_cmd, f"Creating {database}.DBT_ANALYTICS schema")

    # Deploy
    deploy_cmd = ["snow", "dbt", "deploy"]
    if conn:
        deploy_cmd += ["-c", conn]
    deploy_cmd += ["apc", "--source", str(ROOT / "dbt" / "apc"),
                   "--database", database, "--schema", "DBT_ANALYTICS"]
    run_cmd(deploy_cmd, "Deploying dbt project")

    # Build
    build_cmd = ["snow", "dbt", "execute"]
    if conn:
        build_cmd += ["-c", conn]
    build_cmd += ["--database", database, "--schema", "DBT_ANALYTICS", "apc", "build"]
    run_cmd(build_cmd, "Building pipeline (seeds + Dynamic Tables + reconciliation tests)")

    print(f"\n✓ dbt pipeline deployed to {database}.DBT_ANALYTICS")


if __name__ == "__main__":
    main()
