#!/usr/bin/env python3
"""
generate_energy_data.py — Synthetic, Marketplace-shaped energy price indices.

Emits a table that mirrors the LEBA Snowflake Marketplace listings
(EOSE.EUROPEAN_POWER_INDICES / EOSE.UK_GAS_PROMPT_INDICES) column-for-column, so
the demo can run on synthetic data today and swap 1:1 for the real share later
(point dbt's stg_energy_prices at EOSE.* instead of ENERGY_MARKET.ENERGY_PRICE_INDICES).

LEBA schema (from the trial listing data dictionary):
  DATE NUMBER, INDEX VARCHAR, DELIVERY VARCHAR, VOLUME NUMBER, WA FLOAT,
  STATUS NUMBER, FLAG VARCHAR, _META_LOADED_AT TIMESTAMP_NTZ, _META_SOURCE_FILE_NAME VARCHAR

The WA (volume-weighted average price, $/MWh) series is imported from
generate_data.energy_wa so the energy COST component reconciles to this feed.

Usage:
    python3 app/generate_energy_data.py > sql/11_energy_market.sql
    snow sql -c <connection> -f sql/11_energy_market.sql
"""

from generate_data import (
    YEAR_MONTHS,
    COUNTRY_ENERGY_INDEX,
    energy_wa,
    _det_unit,
    chunked_insert,
)

DELIVERY = "Month-Ahead Baseload"


def energy_rows():
    rows = []
    for country, index_name in COUNTRY_ENERGY_INDEX.items():
        for year, months in YEAR_MONTHS:
            for month in months:
                date_int = year * 10000 + month * 100 + 1  # YYYYMMDD, 1st of month
                wa = energy_wa(country, year, month)
                volume = int(40000 + 40000 * _det_unit((country, year, month, "vol")))
                src = f"LEBA_{index_name}_{year}{month:02d}.csv"
                rows.append(
                    f"  ({date_int}, '{index_name}', '{DELIVERY}', {volume}, {wa}, "
                    f"1, 'OK', CURRENT_TIMESTAMP(), '{src}')"
                )
    return rows


def main():
    print("""-- =============================================================================
-- AI Product Costing Accelerator — Synthetic Energy Market Prices
-- =============================================================================
-- Generated by app/generate_energy_data.py
-- Mirrors the LEBA Snowflake Marketplace listings (EOSE.EUROPEAN_POWER_INDICES /
-- EOSE.UK_GAS_PROMPT_INDICES) column-for-column. Synthetic stand-in: swap dbt's
-- stg_energy_prices source to the real EOSE.* share to use live market data.
-- Run: snow sql -c <connection> -f sql/11_energy_market.sql
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS APC_DEPLOY_DB.ENERGY_MARKET
  COMMENT = 'Synthetic stand-in for a Snowflake Marketplace energy price share (LEBA-shaped).';

USE SCHEMA APC_DEPLOY_DB.ENERGY_MARKET;

CREATE OR REPLACE TABLE ENERGY_PRICE_INDICES (
  "DATE"                 NUMBER(38,0)        COMMENT 'Trade date as YYYYMMDD (monthly granularity, 1st of month)',
  "INDEX"                VARCHAR(16777216)   COMMENT 'Market / index name (e.g. UK_POWER, SE_POWER)',
  DELIVERY               VARCHAR(16777216)   COMMENT 'Delivery period (e.g. Month-Ahead Baseload)',
  VOLUME                 NUMBER(38,0)        COMMENT 'Traded volume',
  WA                     FLOAT               COMMENT 'Volume-weighted average price ($/MWh) — the cost driver',
  STATUS                 NUMBER(38,0)        COMMENT 'Index status code',
  FLAG                   VARCHAR(16777216)   COMMENT 'Data quality flag',
  _META_LOADED_AT        TIMESTAMP_NTZ(9)    COMMENT 'Load timestamp',
  _META_SOURCE_FILE_NAME VARCHAR(16777216)   COMMENT 'Source file name'
)
COMMENT = 'LEBA-shaped energy price indices (synthetic). Columns mirror EOSE.EUROPEAN_POWER_INDICES / UK_GAS_PROMPT_INDICES.';
""")
    print(chunked_insert(
        'ENERGY_PRICE_INDICES ("DATE", "INDEX", DELIVERY, VOLUME, WA, STATUS, FLAG, _META_LOADED_AT, _META_SOURCE_FILE_NAME)',
        energy_rows()))
    print("-- Energy market data load complete.")


if __name__ == "__main__":
    main()
